# Generated by Django 6.1.1 on 2026-10-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_package_portfoliophoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='photographerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='portfoliophoto',
            options={'ordering': ['id']},
        ),
    ]
