# Generated by Django 6.1.1 on 2026-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('photographer', 'Fotógrafo'), ('customer', 'Cliente')], default='customer', max_length=12, verbose_name='Rol'),
        ),
    ]
