# Generated by Django 6.1.1 on 2026-10-09 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked account, if any (set when a booking is accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('photographer', 'user'), name='unique_client_user_per_photographer'),
        ),
    ]
