# Generated by Django 6.1.1 on 2026-10-02 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('shoot_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('editing', 'Editing'), ('delivered', 'Delivered')], default='booked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to='clients.client')),
            ],
        ),
    ]
