# Generated by Django 6.1.1 on 2026-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot',
            name='status',
            field=models.CharField(choices=[('booked', 'Reservada'), ('editing', 'En edición'), ('delivered', 'Entregada')], default='booked', max_length=20),
        ),
    ]
