# Generated by Django 6.1.1 on 2026-10-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoots', '0002_alter_shoot_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoot',
            options={'ordering': ['-created_at']},
        ),
    ]
